export const FIND_PRODUCTS_JACKETS_REQUEST = 'FIND_PRODUCT_JACKETS_REQUEST';
export const FIND_PRODUCTS_JACKETS_SUCCESS = 'FIND_PRODUCT_JACKETS_SUCCESS';
export const FIND_PRODUCTS_JACKETS_FAILURE = 'FIND_PRODUCT_JACKETS_FAILURE';