export const FIND_PRODUCTS_SWEATERS_REQUEST = 'FIND_PRODUCT_SWEATERS_REQUEST';
export const FIND_PRODUCTS_SWEATERS_SUCCESS = 'FIND_PRODUCT_SWEATERS_SUCCESS';
export const FIND_PRODUCTS_SWEATERS_FAILURE = 'FIND_PRODUCT_SWEATERS_FAILURE';