export const FIND_PRODUCTS_JEANS_REQUEST = 'FIND_PRODUCT_JEANS_REQUEST';
export const FIND_PRODUCTS_JEANS_SUCCESS = 'FIND_PRODUCT_JEANS_SUCCESS';
export const FIND_PRODUCTS_JEANS_FAILURE = 'FIND_PRODUCT_JEANS_FAILURE';